# Generated by Django 3.2.3 on 2021-05-25 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pp_patient_master',
            fields=[
                ('pp_patm_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('middle_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('dob', models.DateField()),
                ('Address_1', models.CharField(max_length=150)),
                ('Address_2', models.CharField(blank=True, max_length=150)),
                ('Address_3', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pin', models.PositiveIntegerField()),
                ('mobile_no', models.CharField(max_length=12)),
                ('whatsapp_no', models.CharField(max_length=12)),
                ('landline', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(max_length=150)),
                ('facebook', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('linkedlin', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('emergence_contact', models.BigIntegerField()),
                ('blood_group', models.CharField(max_length=4)),
                ('allergy_detail', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('patient_medical_history', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('patient_Family_Historyy', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('status_flag', models.IntegerField()),
                ('last_update_date', models.DateTimeField()),
                ('last_update_by', models.DateTimeField()),
                ('pp_pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pp_patient_master',
            },
        ),
    ]
