# Generated by Django 3.2.3 on 2021-05-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pp_patient_master',
            old_name='patient_Family_Historyy',
            new_name='patient_Family_History',
        ),
    ]
